### ISSUE TITLE
api需要进行一些变化

### ISSUE THREAD

**Issue by no13bus** [ratazzi/v2ex-terminal#1]
1.  setting里面的api_url需要修改为   `api_url: 'https://www.v2ex.com/'`
2.  [336行代码](https://github.com/ratazzi/v2ex-terminal/blob/master/v2ex.py#L336)需要修改为`t = datetime.fromtimestamp(reply['created'])` 因为api返回的值已经变成了int格式了。

**Comment by ratazzi** [comment]
没想到还有人用，这么多年了还是没有完整的 API，搞得我都没有重构的欲望
